auth_node: sh -c 'cd auth_node/ && npm install && npm start'
catalog_python: sh -c 'cd catalog_python/ && pip install -r requirements.txt && python run.py'
cart_node: sh -c 'cd cart_node/ && npm install && npm start'
order_jave: sh -c 'cd order_java/ && gradle run'
api_client_react: sh -c 'cd api_client_react/ && npm install && npm start'